# Indexing BM25 on Wikipedia Corpus

Source is Pyserini's own example:

https://github.com/castorini/pyserini/blob/master/docs/usage-index.md#building-a-bm25-index-embeddable-python-implementation

Steps omitted: extracting jsonl.gz first in my file system and afterwards with tar -xvf. (It has double compression, or I used the wrong decompression method)

## 0. Imports

In [1]:
# Data loading and processing
import polars as pl
import json
import random

random.seed(42)

# Retrieval
from pyserini.search.lucene import LuceneSearcher
from sentence_transformers import CrossEncoder

# LLM
from transformers import AutoModelForCausalLM, AutoTokenizer

# Uncertainty Estimation
import TruthTorchLM as ttlm

# Displaying
from IPython.display import display, Markdown
from tqdm import tqdm

import logging
logging.disable(logging.WARNING)

WARNING: Using incubator modules: jdk.incubator.vector

## 1. Prompts

We take 50 prompts from longform-objects and Factscore-bio

In [24]:
factscore_bio = pl.read_ndjson("data/labeled_data/ChatGPT.jsonl")
factscore_prompts = factscore_bio.get_column("input").to_list()
factscore_prompts

['Question: Tell me a bio of Lanny Flaherty.',
 'Question: Tell me a bio of Marianne McAndrew.',
 'Question: Tell me a bio of Chaim Malinowitz.',
 'Question: Tell me a bio of Doug Sheehan.',
 'Question: Tell me a bio of Gerhard Fischer (inventor).',
 'Question: Tell me a bio of Chief Jones.',
 'Question: Tell me a bio of Focus....',
 'Question: Tell me a bio of Joey D. Vieira.',
 'Question: Tell me a bio of Taral Hicks.',
 'Question: Tell me a bio of Lees Knowles.',
 'Question: Tell me a bio of Carolina Portesi Peroni.',
 'Question: Tell me a bio of Quintus Sosius Senecio.',
 'Question: Tell me a bio of Joeri Adams.',
 'Question: Tell me a bio of Dominic King.',
 'Question: Tell me a bio of Vincenzo Tusa.',
 'Question: Tell me a bio of Jean Daullé.',
 'Question: Tell me a bio of Richard Burkewood Welbourn.',
 'Question: Tell me a bio of Damir Memović.',
 'Question: Tell me a bio of María Elena Medina-Mora Icaza.',
 'Question: Tell me a bio of Hesham Nazih.',
 'Question: Tell me a bio of Luis Guillermo Rivera.',
 'Question: Tell me a bio of Desmond Luke.',
 'Question: Tell me a bio of Miguel Díaz (baseball).',
 'Question: Tell me a bio of Roxana Díaz (athlete).',
 'Question: Tell me a bio of Fernando (footballer, born 1984).',
 'Question: Tell me a bio of Gerardo Fernandez Fe.',
 'Question: Tell me a bio of Augusto Martínez Sánchez.',
 'Question: Tell me a bio of Sharad Kumar (athlete).',
 'Question: Tell me a bio of Ko Itakura.',
 'Question: Tell me a bio of Besant Ravi.',
 'Question: Tell me a bio of Thomas Houghton (rugby league).',
 'Question: Tell me a bio of Katsunosuke Hori.',
 'Question: Tell me a bio of Ra Jong-yil.',
 'Question: Tell me a bio of Song Kang.',
 'Question: Tell me a bio of Rin Iwanaga.',
 'Question: Tell me a bio of Keita Kadokura.',
 'Question: Tell me a bio of Lily Branscombe.',
 'Question: Tell me a bio of Luis N. Rivera-Pagán.',
 'Question: Tell me a bio of Jesse Foppert.',
 'Question: Tell me a bio of Mike Trivisonno.',
 'Question: Tell me a bio of Zelma Wilson.',
 'Question: Tell me a bio of Michael Valpy.',
 'Question: Tell me a bio of Prince Rivers.',
 'Question: Tell me a bio of John Estes.',
 'Question: Tell me a bio of Eric Hacker.',
 'Question: Tell me a bio of Alma Katsu.',
 'Question: Tell me a bio of Carlos Alfonso.',
 'Question: Tell me a bio of Rennie Fritchie, Baroness Fritchie.',
 'Question: Tell me a bio of Daniel Charles.',
 'Question: Tell me a bio of Zamfir Arbore.',
 'Question: Tell me a bio of Kourosh Zolani.',
 'Question: Tell me a bio of Marie Alexandrine Becker.',
 'Question: Tell me a bio of Francesco Mimbelli.',
 'Question: Tell me a bio of Frederick Howard Taylor.',
 'Question: Tell me a bio of Bella Akhmadulina.',
 'Question: Tell me a bio of Lewis Nkosi.',
 'Question: Tell me a bio of Samuel Oboh.',
 'Question: Tell me a bio of Idriss Ngari.',
 'Question: Tell me a bio of Regina Martínez Pérez.',
 'Question: Tell me a bio of Baltasar Corrada del Río.',
 'Question: Tell me a bio of Manuel Salazar (footballer).',
 'Question: Tell me a bio of Malcolm Hedding.',
 'Question: Tell me a bio of Antonio Gasalla.',
 'Question: Tell me a bio of Gonzalo Fonseca.',
 'Question: Tell me a bio of Hibo Wardere.',
 'Question: Tell me a bio of Toyoko Tokiwa.',
 'Question: Tell me a bio of Shayne Neumann.',
 'Question: Tell me a bio of Matthew Tukaki.',
 'Question: Tell me a bio of Wahida Prism Khan.',
 'Question: Tell me a bio of Antonio Diaz (Filipino politician).',
 'Question: Tell me a bio of Ben Lummis.',
 'Question: Tell me a bio of Siti Rahmah Kassim.',
 'Question: Tell me a bio of Nisar Ahmad Kakru.',
 'Question: Tell me a bio of Jagan.',
 'Question: Tell me a bio of Don Featherstone (artist).',
 'Question: Tell me a bio of Travis Oliphant.',
 'Question: Tell me a bio of Julia Faye.',
 'Question: Tell me a bio of Kim Burrell.',
 'Question: Tell me a bio of Craig Morton.',
 'Question: Tell me a bio of Virginia Valli.',
 'Question: Tell me a bio of William Post.',
 'Question: Tell me a bio of Rob Furlong.',
 'Question: Tell me a bio of Milton Diamond.',
 'Question: Tell me a bio of Fran Unsworth.',
 'Question: Tell me a bio of Robert Smith, Baron Smith of Kelvin.',
 'Question: Tell me a bio of Sian Massey-Ellis.',
 "Question: Tell me a bio of Paul O'Neill (racing driver).",
 'Question: Tell me a bio of William Waldegrave, Baron Waldegrave of North Hill.',
 'Question: Tell me a bio of Alexandre Guilmant.',
 'Question: Tell me a bio of Oliver Letwin.',
 'Question: Tell me a bio of Terence Blacker.',
 'Question: Tell me a bio of Alberto Malesani.',
 'Question: Tell me a bio of Jessica Barboza.',
 'Question: Tell me a bio of Andreas Kisser.',
 'Question: Tell me a bio of Ramesses IV.',
 'Question: Tell me a bio of Scientist (musician).',
 'Question: Tell me a bio of Daniel Carvalho.',
 'Question: Tell me a bio of Waruhiu Itote.',
 'Question: Tell me a bio of Henry Santos.',
 'Question: Tell me a bio of Martín Lousteau.',
 'Question: Tell me a bio of Florencia Bertotti.',
 'Question: Tell me a bio of Jonathan Haagensen.',
 'Question: Tell me a bio of Ylona Garcia.',
 'Question: Tell me a bio of Kerser.',
 'Question: Tell me a bio of Shashank Manohar.',
 'Question: Tell me a bio of Emmett Skilton.',
 'Question: Tell me a bio of Samantha Ruth Prabhu.',
 'Question: Tell me a bio of Botak Chin.',
 'Question: Tell me a bio of Kim Casali.',
 'Question: Tell me a bio of Takeo Miki.',
 'Question: Tell me a bio of Chris Cheney.',
 'Question: Tell me a bio of Owen Wright (surfer).',
 'Question: Tell me a bio of Jonathan Tucker.',
 'Question: Tell me a bio of Anna May Wong.',
 'Question: Tell me a bio of Mitzi Gaynor.',
 'Question: Tell me a bio of Sara Paxton.',
 'Question: Tell me a bio of Waka Flocka Flame.',
 'Question: Tell me a bio of Andrew Shue.',
 'Question: Tell me a bio of James B. Donovan.',
 'Question: Tell me a bio of George Cukor.',
 'Question: Tell me a bio of Darrius Heyward-Bey.',
 'Question: Tell me a bio of António de Oliveira Salazar.',
 'Question: Tell me a bio of Shahnaz Pahlavi.',
 'Question: Tell me a bio of Egon Krenz.',
 'Question: Tell me a bio of Vaira Vīķe-Freiberga.',
 'Question: Tell me a bio of Heinrich Harrer.',
 'Question: Tell me a bio of Annika Sörenstam.',
 'Question: Tell me a bio of Daniel Dubois (boxer).',
 'Question: Tell me a bio of Robert Louis Stevenson.',
 'Question: Tell me a bio of Glover Teixeira.',
 'Question: Tell me a bio of Garrincha.',
 'Question: Tell me a bio of Gabriela Sabatini.',
 'Question: Tell me a bio of José Sánchez del Río.',
 'Question: Tell me a bio of Abdou Diallo.',
 'Question: Tell me a bio of Paul Kruger.',
 'Question: Tell me a bio of Beenie Man.',
 'Question: Tell me a bio of Roberto Clemente.',
 'Question: Tell me a bio of Gilberto Silva.',
 'Question: Tell me a bio of Sajid Nadiadwala.',
 'Question: Tell me a bio of Ram Gopal Varma.',
 'Question: Tell me a bio of Maneka Gandhi.',
 'Question: Tell me a bio of David Wenham.',
 'Question: Tell me a bio of Jimmy Bartel.',
 'Question: Tell me a bio of Wendy (singer).',
 'Question: Tell me a bio of Cha Seung-won.',
 'Question: Tell me a bio of Kyu Sakamoto.',
 'Question: Tell me a bio of Kang Ji-hwan.',
 'Question: Tell me a bio of Lauren London.',
 'Question: Tell me a bio of Harrison Ford.',
 'Question: Tell me a bio of Nikki Sixx.',
 'Question: Tell me a bio of Kyra Sedgwick.',
 'Question: Tell me a bio of James Taylor.',
 'Question: Tell me a bio of Chadwick Boseman.',
 'Question: Tell me a bio of Eliza Dushku.',
 'Question: Tell me a bio of Bridget Moynahan.',
 'Question: Tell me a bio of Errol Flynn.',
 'Question: Tell me a bio of Osama bin Laden.',
 'Question: Tell me a bio of Jack Leach.',
 'Question: Tell me a bio of Adil Rami.',
 'Question: Tell me a bio of Kalki Koechlin.',
 'Question: Tell me a bio of Vanessa Kirby.',
 'Question: Tell me a bio of Liam Payne.',
 'Question: Tell me a bio of Elsa Pataky.',
 'Question: Tell me a bio of Carlos Santana.',
 'Question: Tell me a bio of Tiffany Haddish.',
 'Question: Tell me a bio of Lina Medina.',
 'Question: Tell me a bio of Jidenna.',
 'Question: Tell me a bio of Mauro Icardi.',
 'Question: Tell me a bio of Mohamed Salah.',
 'Question: Tell me a bio of Canelo Álvarez.',
 'Question: Tell me a bio of Ronaldo (Brazilian footballer).',
 'Question: Tell me a bio of Lua Blanco.',
 'Question: Tell me a bio of Roselyn Sánchez.',
 'Question: Tell me a bio of Toru Muranishi.',
 'Question: Tell me a bio of Teresa Palmer.',
 'Question: Tell me a bio of Anushka Sharma.',
 'Question: Tell me a bio of Rakhi Sawant.',
 'Question: Tell me a bio of IU (singer).',
 'Question: Tell me a bio of Taika Waititi.',
 'Question: Tell me a bio of Kang Daniel.',
 'Question: Tell me a bio of Tim Fischer.',
 'Question: Tell me a bio of Ji Sung.',
 'Question: Tell me a bio of Dacre Montgomery.']

In [ ]:
longfact_objects = pl.read_ndjson("data/longfact-objects_gpt4_01-12-2024_noduplicates/*.jsonl")
longfact_prompts = longfact_objects.get_column("prompt").to_list()
longfact_prompts

['Who is Michael B. Jordan?',
 'Could you provide some details about the Hague Conventions?',
 "What led to Frank Lloyd Wright's design choice for the circular shape of the Guggenheim Museum in New York City?",
 'Who is George Pimentel and how has his development of the chemical laser modified the field of physical chemistry and spectroscopic analysis?',
 'What is the Google Cloud AutoML service for machine learning?',
 'What was the ethical controversy surrounding the Facebook Live killer?',
 'Who is Zygmunt Bauman?',
 'Who is Michael Wildes?',
 'Could you provide an overview of Nike\'s "Just Do It" marketing campaign?',
 'Who is Norbert Elias?',
 'Who is Paul Langerhans?',
 'Can you delve into the approach of McDonald\'s "I\'m Lovin\' It" promotional strategy?',
 'What was the ethical controversy surrounding the phone-hacking by News of the World?',
 'What is the music festival "Glastonbury"?',
 'What can you tell me about the Rocky Mountains?',
 'What is the Fields Medal?',
 'What is the role of Richard Edelman in Edelman Public Relations?',
 'Who is Bruno Latour?',
 'Who is Cedric Villani?',
 'What can you tell me about the Amazonian giant centipede?',
 'What can you tell me about the Kakapo?',
 'Can you describe the Great Barrier Reef?',
 'Who is Chief Justice Earl Warren?',
 'Could you explain what the Event Horizon Telescope is?',
 "What was Peter Drucker's role at General Motors?",
 'Who is Euclid?',
 'What is the aim of The Minnesota Twin Study in the context of nature vs nurture debate?',
 'What can you tell me about the Arab Spring?',
 'Can you detail the aspects of Budweiser\'s "Whassup" marketing campaign?',
 'Can you tell me about the Tokyo Stock Exchange?',
 'What is the IBM Watson AI?',
 'Who is Jodie Comer?',
 'What was the basis of Dove\'s "Real Beauty" marketing campaign?',
 'What was the ethical controversy surrounding the genetic modification of babies by Chinese scientist He Jiankui?',
 'Who is Benjamin Spock?',
 'What is the Olduvai Gorge?',
 'What\'s the concept of Gillette\'s "The Best a Man Can Get" campaign?',
 'What can you tell me about the design of the Flatiron Building in New York, designed by Daniel Burnham?',
 "How did Apple's public relations team handle the criticism related to the “Batterygate” throttling controversy in 2017?",
 'Could you tell me about the Comet Hale-Bopp?',
 'Who is Terence Tao?',
 'What is the Swine flu pandemic of 2009?',
 'What can you tell me about the Maastricht Treaty?',
 'Who is Jack Dorsey and what is his role at Twitter?',
 'What is the Asian lineage Avian influenza A(H7N9) virus?',
 'What was the architectural inspiration behind the design of the Leaning Tower of Pisa?',
 'Who is Sandra Bullock?',
 'Can you describe the Niagara Falls?',
 "What is Microsoft's Azure Machine Learning Studio?",
 'What is the primary focus of the Famous Marshmallow Experiment conducted by Walter Mischel?',
 'What can you tell me about the Bird of Paradise flower?',
 'What is the cybersecurity firm Kaspersky Lab?',
 'What is the role of the Central Bank of Russia?',
 'What is the function of the U-Visa under US Immigration Law?',
 "What is the controversy involving Foxconn's labor practices in its electronics manufacturing plants?",
 'Can you explain what the Amprobe AT-3500 Underground Cable Locator is used for?',
 'Who is Peter Singer?',
 'Who is Blaise Pascal?',
 'What can you tell me about the Serengeti National Park?',
 'Who is Cyrus D. Mehta in the field of Immigration Law?',
 'Can you provide information about the Vienna Convention on Diplomatic Relations?',
 'What can you tell me about the coronation of Queen Elizabeth II?',
 'Who is Yoshua Bengio?',
 'Can you provide information about the Financial Crimes Enforcement Network (FinCEN)?',
 'Who is Robert Tappan Morris?',
 "What is the importance of Antarctica's ice sheets?",
 'Can you tell me about the Swaminarayan Akshardham in Delhi in Hinduism?',
 'Who is Ludwig Wittgenstein?',
 'What can you tell me about the LIGO Scientific Collaboration (LSC)?',
 'What is the Laetoli Footprint Trail?',
 "Could you tell me about the specific events that took place during the Enigma Machine's capture in 1941?",
 'Can you discuss the tactics utilized in Starbucks\' "Meet Me at Starbucks" marketing campaign?',
 'What is the Polio epidemic of 1952?',
 'Who is the pianist "Lang Lang"?',
 'Who is George Simmel?',
 'What can you tell me about the assassination of Archduke Franz Ferdinand?',
 'Who is Lil Nas X?',
 'What is the Y2K bug?',
 'Who is Lama Zopa Rinpoche?',
 'Who is Gottfried Wilhelm Leibniz?',
 'Who is Daniel Kahneman in the field of behavioral economics?',
 'Who is Alfred Adler and his contribution to the study of individual psychology?',
 'Who is John Bolton?',
 'Who is Max Theiler?',
 'Who is Susan Wojcicki and what is her role at YouTube?',
 "What steps did Boeing's public relations team take to address safety concerns following the 737 MAX crashes in 2018 and 2019?",
 'What transpired during the bombing of Hiroshima and Nagasaki in 1945?',
 'Who is the cybersecurity journalist Brian Krebs?',
 'Tell me about the Immigration Act of 1990.',
 'Who is Timothée Chalamet?',
 'What is the Pech Merle Cave?',
 'What can you tell me about the Ghost Orchid?',
 'Who is Idris Elba?',
 'What is the McGill University Health Centre?',
 'Who is Rosalind Franklin and how did her work with X-ray diffraction images contribute to the understanding of the molecular structure of DNA?',
 "What can you tell me about St. Peter's Basilica in the Vatican City?",
 'Who is Stamen Grigorov?',
 'Can you describe what happened during the politically-motivated Munich Massacre at the 1972 Summer Olympics?',
 'What can you tell me about the Ashanti Empire?',
 'Who is Daniel Craig?',
 'What is the Fast.ai organization?',
 "What is the controversy regarding Apple's tax avoidance schemes?",
 'What can you tell me about the management style of Ursula Burns during her time as CEO of Xerox?',
 "Can you provide information on Frederick Law Olmsted's work on Central Park?",
 'Who is lawyer Gloria Allred?',
 'Can you give me details about the Institute of Management Accountants (IMA)?',
 'What strategy did Volkswagen\'s public relations team implement to address the "Dieselgate" emission scandal in 2015?',
 'Who is Mary Barra?',
 'What is the controversy involving the Theranos blood testing scandal?',
 'Who is Andrew Wiles?',
 "What is the PerkinElmer's Atomic Absorption Spectrometer (AAS) often employed for in quantitative analysis of metal ions in aqueous solutions?",
 'What is the album "Sgt. Pepper\'s Lonely Hearts Club Band" by The Beatles?',
 'What is the Cassini-Huygens Spacecraft?',
 'What was the controversy surrounding the wage practices of the convenience store chain, 7-Eleven?',
 'Who is the drummer "Neil Peart"?',
 'What is the role of the Keysight N6700 Low-Profile Modular Power System in an electronic testing environment?',
 'Who is the songwriter "Bob Dylan"?',
 'Who is Hannah Arendt?',
 'What can you tell me about the World Trade Organization?',
 "What was the United States' role in the Kyoto Protocol?",
 'Who is Nathan Wolfe?',
 'Who is Haile Selassie in Rastafarianism?',
 'What strategies did BP utilize in the public relations aftermath of the Deepwater Horizon oil spill in 2010?',
 "What is the movie 'A Ghost Story'?",
 'Who is Benoit Mandelbrot?',
 'What is the password manager LastPass?',
 'What can you tell me about the Treaty of Tordesillas?',
 'Who is Abraham Maslow in the field of Humanistic Psychology?',
 'What transpired during the Soweto Uprising in South Africa?',
 'What can you tell me about the assassination of Martin Luther King Jr.?',
 'Who is Ignaz Semmelweis?',
 'Who is Albert Camus?',
 "Can you tell me about the TRIUMF, Canada's national particle accelerator facility?",
 'Can you provide an overview of the Federal Reserve Bank of New York?',
 'What are some of the characteristics of the Centre Pompidou designed by Renzo Piano and Richard Rogers?',
 "What is the controversy behind Nestle's baby milk scandal?",
 'What can you tell me about the Mojave Desert?',
 "What is the purpose of Stanford's Binet Intelligence Test in the field of child psychology?",
 'Who is Noam Chomsky in the field of cognitive psychology?',
 'Who is the music video director "Hype Williams"?',
 "What actions did PepsiCo's public relations team take in response to the backlash for the Kendall Jenner ad in 2017?",
 'What is the video game company, "Rockstar Games"?',
 'Who is Doja Cat?',
 'What does the EB-5 Immigrant Investor Program under US Immigration Law entail?',
 'Who is Albert Sabin?',
 'Who is Justice Sonia Sotomayor?',
 'What is the significance of the Sagrada Familia in Barcelona?',
 'Who is Gertrude B. Elion and how has her groundbreaking work on the synthesis of medical drugs from regular compounds influenced pharmaceutical chemistry?',
 'What is the Ronald Reagan UCLA Medical Center?',
 'How is the United States related to the East Asia Summit (EAS)?',
 'What can you tell me about the Hindenburg disaster?',
 'What is the Ryder Cup?',
 'Can you share some information about the Convention on the Elimination of All Forms of Discrimination Against Women (CEDAW)?',
 'Who is the character Sam Porter Bridges from the game "Death Stranding"?',
 'What is known about the Peace of Westphalia?',
 'What is the Dolmen of Menga?',
 'What is the Merck & Co., Inc.?',
 'Can you describe what happened in the Apollo 13 mission?',
 'What is the IBM Watson system?',
 'Who is Richard Stallman?',
 'Who is Theodor W. Adorno?',
 "What is the America's Cup?",
 'What is the video game developer "FromSoftware"?',
 'What is the Robert Koch Institute?',
 'What is the Chandra X-ray Observatory?',
 'Who is Edward Bernays?',
 'Who is Samantha Power in the context of U.S. foreign policy?',
 'Who is Svante Arrhenius and how did he contribute to our understanding of electrolytic dissociation?',
 'Can you provide an overview of the World Bank Group?',
 'What is the function of the Central Bank of Brazil?',
 'Who is Michael Atiyah?',
 'Can you provide some details about the North Atlantic Treaty?',
 'Who is George Herbert Mead?',
 'Tell me about the Dead Sea.',
 'Who is Billie Jean King?',
 'Can you explain what the Mahabodhi Temple is in Buddhism?',
 'What transpired during the Cuban Missile Crisis in 1962?',
 'Who is Andreas Vesalius?',
 'Who is Adrian Lamo?',
 'Who is lawyer Robert Kardashian?',
 'Who is Arthur Schopenhauer?',
 'Who is Mia Hamm?',
 'What is the King Faisal Specialist Hospital and Research Centre?',
 'What is the software Norton Antivirus?',
 'Who is Ian Lipkin?',
 'Who is Michel Foucault?',
 'Who is Pythagoras?',
 'What can you tell me about the Dead Sea?',
 'What is the encryption tool VeraCrypt?',
 'What is the controversy associated with the British Petroleum (BP) Deepwater Horizon oil spill?',
 "What is the movie 'The Grand Budapest Hotel'?",
 'Who is Zalmay Khalilzad?',
 'Can you provide information about the Public Company Accounting Oversight Board?',
 'Who is Prerna Lal in the field of Immigration Law?',
 'What is the Amazon Web Services (AWS)?',
 'Can you tell me about the asteroid Vesta?',
 'Who is Millie Bobby Brown?',
 'What is the Raspberry Pi Zero?',
 "What is the controversy surrounding Lockheed Martin's involvement in the Yemen war?",
 'What is the PyTorch machine learning library?',
 "What is the Thermo Fisher Scientific's Inductively Coupled Plasma Mass Spectrometry (ICP-MS) commonly used for in trace elemental analysis?",
 'Tell me about the law firm Fragomen, Del Rey, Bernsen & Loewy.',
 'Who is Maria Sharapova?',
 'What is the Hendra virus outbreak of 1994 in Australia?',
 'What is the cybersecurity event Black Hat Conference?',
 'What is the significance of the Kepler Space Observatory?',
 'Can you explain what the Keysight 33500B Series waveform generators are used for?',
 'What can you tell me about the Archaeopteryx?',
 'What is the Bronze Age Nuragic civilization?',
 "What is the movie 'Pulp Fiction'?",
 'What is the NLTK library for machine learning?',
 'How did McDonald\'s handle public relations following the infamous "hot coffee" lawsuit in 1994?',
 'What is the cybersecurity tool Wireshark?',
 'What can you tell me about the Giant Sequoia?',
 'What is the Decision Tree Algorithm in the field of machine learning?',
 'What is the Google Brain team?',
 'Who is Robert Gallo?',
 'Who is Reed Hastings and what was his role at Netflix?',
 "What is the movie 'Call Me By Your Name'?",
 'Who is the character Master Chief in the Halo series?',
 'Who is Paul L. Modrich?',
 'Can you tell me about Stonehenge?',
 'Who is Erik Erikson known for his work on the stages of psychosocial development?',
 'What is the Microsoft Quantum Development Kit?',
 "How did United Airlines' public relations team handle the fallout of a passenger being dragged off the flight in 2017?",
 'Can you provide information about the Certified General Accountants Association of Canada?',
 'What can you tell me about Victoria Falls?',
 'Who is Jacques Derrida?',
 'Who is the singer "Billie Holiday"?',
 'Who is Geoffrey Hinton?',
 'Can you provide details about the Treaty on the Non-Proliferation of Nuclear Weapons?',
 'Who is Fritz Haber, known for the Haber process?',
 'Can you tell me about The Louvre Museum?',
 "What is the movie 'The Room'?",
 'Can you tell me about the Atacama Large Millimeter/submillimeter Array (ALMA)?',
 'What is the Cosquer Cave?',
 'What is the La Brea Tar Pits?',
 'Who is William James?',
 'Can you provide details about the International Accounting Standards Board?',
 'What is the Iran Nuclear Deal and what was the involvement of the United States in it?',
 'Can you provide information about the star system, Alpha Centauri?',
 'Can you provide an overview of the International Monetary Fund?',
 'What can you tell me about the Gold Rush in California?',
 'Who is lawyer Alan Dershowitz?',
 'How did the architects integrate the surrounding nature into the design of the Getty Center in Los Angeles?',
 'What was the controversy behind the Uber Greyball program?',
 'Who is Elizabeth Blackwell?',
 'What is the eSports organization "Cloud9"?',
 "Can you provide information about Marillyn Hewson's tenure as CEO of Lockheed Martin?",
 'What can you tell me about Yellowstone National Park?',
 'Can you provide some information about the Palomar Observatory?',
 'What is the secure messaging app Signal?',
 'What is the Garmada Cave?',
 'What can you tell me about the Battle of Thermopylae?',
 'What is the Spitzer Space Telescope?',
 'What was the ethical controversy surrounding the Milgram Experiment?',
 'Who is Paul Ekman in the study of emotional and facial expressions?',
 'What is the Royal Children’s Hospital, Melbourne?',
 'What does the Scotia International Limited company do?',
 'What role does the United States play in the Arab League?',
 'Who is Kary Mullis and how did his invention of polymerase chain reaction (PCR) revolutionize DNA research and diagnostics in molecular chemistry?',
 'What was the purpose of Operation Just Cause?',
 "What is the controversy associated with Amazon's workplace conditions?",
 'What was the ethical controversy surrounding the Exxon Valdez oil spill?',
 'Can you describe the events that unfolded during the assassination of Mahatma Gandhi in 1948?',
 'Who is Joseph-Louis Lagrange?',
 'What is the Altamira Cave?',
 'What can you tell me about the Mariana Trench?',
 'What can you tell me about the Bubonic Plague in Europe?',
 'Who is John Stuart Mill?',
 "What was the ethical controversy surrounding the privacy invasion by Snowden's NSA leaks?",
 'What is the controversy behind the Wells Fargo account fraud scandal?',
 "Can you tell me about the 1984 Bhopal gas tragedy and Union Carbide's public relations response?",
 'What is the Human immunodeficiency virus (HIV) pandemic?',
 'What is the Clovis culture?',
 'Can you describe the Nile River in Africa?',
 'What is the recording studio "Abbey Road Studios"?',
 'What are the features of the Tektronix TDS1002B Digital Storage Oscilloscope in signal analysis?',
 'Can you explain what happened during the Suez Canal Crisis in 1956?',
 'What is the role of the Amazon River in South America?',
 'Can you tell me about the GE Multilin 750 Relay in power system protection?',
 'Can you detail the components of Amazon\'s "Prime Day" promotional event?',
 'Can you tell me about the Lumbini in Nepal in Buddhism?',
 'What underpinned the design choice for the Shard skyscraper in London, designed by Renzo Piano?',
 'What is the usage of the Fluke 435 Series II Power Quality and Energy Analyzer in monitoring power consumption?',
 'What is the jazz club "Blue Note"?',
 "Can you provide information about Jack Ma's time as the Executive Chairman of Alibaba Group?",
 'Can you provide information about the integrated accounting system Tally.ERP 9?',
 'Who is Edward A. Feigenbaum?',
 'Can you provide details about the Journal of Accounting and Economics?',
 'What is the ENIAC computer?',
 'What can you tell me about the Sagittarius A*?',
 'What can you tell me about the Boxer Rebellion?',
 'Who is Georg Wilhelm Friedrich Hegel?',
 'Who is Linus Torvalds?',
 'Who is Bonnie Gibson in the field of Immigration Law?',
 'What is the Petralona Cave?',
 "How did Starbucks' public relations department respond to the arrests of two black men in Philadelphia in 2018?",
 'Who is Robert Merton?',
 'What is the hacking collective Anonymous?',
 'Can you explain the use of the National Instruments CompactRIO controller in control systems and data acquisition? ',
 'What took place during the fall of the Berlin Wall in 1989?',
 'What is the function of the I-589, Application for Asylum and for Withholding of Removal in US Immigration Law?',
 'Who is Philip Zimbardo?',
 'What is the controversy regarding the Equifax data breach?',
 'Can you provide information on the Reserve Bank of India?',
 'What can you share about the Treaty of Lisbon?',
 'What are the main responsibilities of the African Development Bank Group?',
 'Who is Lao Tzu?',
 'What is the Iditarod Trail Sled Dog Race?',
 'Could you tell me about the events that occurred during the Jonestown Massacre in 1978?',
 'What can you tell me about the Ural Mountains?',
 'Who is the character Marcus Fenix in the Gears of War series?',
 'Could you explain what the Mars Rover Curiosity is?',
 'Who is lawyer Clarence Darrow?',
 'Can you provide information on the Audit Analytics software?',
 'What can you tell me about the Salem Witch Trials?',
 "What is Tesler's Law of the Conservation of Complexity?",
 "What can you tell me about Sundar Pichai's leadership at Google?",
 'What is the approach behind Google\'s "Year in Search" marketing strategy?',
 'Who is Thomas Wellems?',
 'Who is Jeh Johnson in the field of Immigration Law?',
 'What can you tell me about the Greenland Ice Sheet?',
 'What is the La Cotte de St Brelade?',
 'Who is Albert Osterhaus?',
 'What is the Grotte du Grand Roc?',
 'Who is Georg Lukács?',
 'Who is Patricia Hill Collins?',
 'What is the Great Synagogue of Sydney?',
 'Who is the guitarist "B.B. King"?',
 'What is the virtual private network software, NordVPN?',
 'Who is Justice Ruth Bader Ginsburg?',
 "What is Eliezer Yudkowsky's Machine Intelligence Research Institute?",
 'Can you tell me about the Vatican City?',
 'What can you tell me about the Amazon River?',
 'What can you tell me about the Great Fire of Rome?',
 'Who is Maryam Mirzakhani?',
 'Who is lawyer Marcia Clark?',
 'Who is Ira J. Kurzban?',
 'What is the Royal Victoria Hospital?',
 'Can you tell me about the Australian Securities and Investments Commission?',
 'Who is Immanuel Wallerstein?',
 'What can you tell me about the invasion of Normandy?',
 'How does the Eaton Powerware 9355 UPS perform in protecting critical systems from power disturbances?',
 'What is the role of the International Monetary Fund in the global economy?',

In [4]:
prompts = random.sample(factscore_prompts,25) + random.sample(longfact_prompts,25)
prompts

['Question: Tell me a bio of Mitzi Gaynor.',
 'Question: Tell me a bio of Gerardo Fernandez Fe.',
 'Question: Tell me a bio of Waruhiu Itote.',
 'Question: Tell me a bio of Siti Rahmah Kassim.',
 'Question: Tell me a bio of Prince Rivers.',
 'Question: Tell me a bio of Jimmy Bartel.',
 'Question: Tell me a bio of Shashank Manohar.',
 'Question: Tell me a bio of Oliver Letwin.',
 'Question: Tell me a bio of Francesco Mimbelli.',
 'Question: Tell me a bio of Ra Jong-yil.',
 'Question: Tell me a bio of Thomas Houghton (rugby league).',
 'Question: Tell me a bio of Scientist (musician).',
 'Question: Tell me a bio of Jesse Foppert.',
 'Question: Tell me a bio of Regina Martínez Pérez.',
 'Question: Tell me a bio of Manuel Salazar (footballer).',
 'Question: Tell me a bio of Sharad Kumar (athlete).',
 'Question: Tell me a bio of Gerardo Fernandez Fe.',
 'Question: Tell me a bio of Tiffany Haddish.',
 'Question: Tell me a bio of Eric Hacker.',
 'Question: Tell me a bio of Vaira Vīķe-Freiberga.',
 'Question: Tell me a bio of Jonathan Haagensen.',
 'Question: Tell me a bio of Focus....',
 'Question: Tell me a bio of Carlos Santana.',
 'Question: Tell me a bio of Lina Medina.',
 'Question: Tell me a bio of Kalki Koechlin.',
 'Who is the character Geralt of Rivia from The Witcher series?',
 "Can you provide information about Marillyn Hewson's tenure as CEO of Lockheed Martin?",
 "What is the controversy involving Foxconn's labor practices in its electronics manufacturing plants?",
 'What was the controversy behind the Uber Greyball program?',
 'Who is Dr. Virginia Apgar?',
 "What is the controversy behind Nestle's baby milk scandal?",
 'Who is Jacques Hadamard?',
 'What was the basis of Dove\'s "Real Beauty" marketing campaign?',
 'What is the purpose of the Form N-400 in US Immigration Law?',
 'Can you provide information about the Financial Crimes Enforcement Network (FinCEN)?',
 'What is the Cueva de las Manos?',
 'Who is Nathan Wolfe?',
 'What is the Shimadzu Gas Chromatograph used for in the separation and analysis of volatile compounds?',
 'Who is Carl Linnaeus?',
 'Who is Dian Fossey?',
 "What do you know about the Baha'i House of Worship in Wilmette?",
 'Who is Roscoe Pound?',
 'Who is Michael Atiyah?',
 'How does the ABB ACS880 Industrial Drives function in an industrial setting?',
 'What is the Large Synoptic Survey Telescope?',
 'What are the key architectural features of the Notre-Dame Cathedral in Paris?',
 'What can you tell me about the Mariana Trench?',
 'What is known about the Kyoto Protocol?',
 'What can you tell me about the Eastern long-necked turtle?',
 'What can you tell me about the Danube River?']

## 1. Retrieval

First an index is made:

This uses DefaultLuceneDocumentGenerator which already by default features stopword removal and stemming

- I have 14 threads, so I use half of them. More might be faster, but this seemed safe
- "--storePositions" "--storeDocvectors" "--storeRaw" are expensive options but we need the raw documents for reranking.

In [5]:
# !python -m pyserini.index.lucene \
#   --collection JsonCollection \
#   --input data/data00/jiajie_jin/flashrag_indexes/wiki_dpr_100w \
#   --index indexes/wiki_dump \
#   --generator DefaultLuceneDocumentGenerator \
#   --threads 7 \
#   --storePositions --storeDocvectors --storeRaw

### Test BM25

In [6]:
prompt = prompts[0]

print(f"Query: \"{prompt}\"\n")

searcher = LuceneSearcher('index/wiki_dump')
hits = searcher.search(prompt,k=1000)

print("BM25 results:")
docs = [json.loads(hits[i].lucene_document.get('raw'))["contents"] for i in range(len(hits))]
docs[:3]

Query: "Question: Tell me a bio of Mitzi Gaynor."

BM25 results:

Nov 24, 2025 9:25:56 PM org.apache.lucene.store.MemorySegmentIndexInputProvider <init>
INFO: Using MemorySegmentIndexInput with Java 21; to disable start with -Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false

['"Mitzi Gaynor"\nis the best thing since... ""Mitzi Gaynor!"" Lisa exclaims. In episode 2 of ""Monty Python\'s Fliegender Zirkus"", Connie Booth played Princess Mitzi Gaynor in ""The Tale of Happy Valley"". Mitzi Gaynor is mentioned on ""The Marvelous Mrs. Maisel"" in Episode 4, ""The Disappointment of the Dionne Quintuplets"". Mitzi Gaynor Mitzi Gaynor (born Francesca Marlene de Czanyi von Gerber; September 4, 1931) is an American actress, singer, and dancer. Her notable films include ""There\'s No Business Like Show Business"" (1954), which featured Irving Berlin\'s music and also starred Ethel Merman, Dan Dailey, Marilyn Monroe, Donald O\'Connor, and Johnnie Ray; and ""South',
 '"Mitzi Gaynor"\ntheatrical performer, then in films like ""There\'s No Business Like Show Business"", ""Les Girls"", and ""South Pacific"", and finally as a concert performer. In ""The Simpsons"" episode ""All About Lisa"" Sideshow Mel takes Lisa Simpson aside when she becomes Krusty the Clown\'s assistant. He tells her that the key to dealing with Krusty is to always be prepared to cater to his needs—have a cigar at the ready, never directly look him in the eye, and pretend to know who Mitzi Gaynor is if he mentions her – he always does. She then uses this reference when Krusty says Lisa',
 '"Mitzi Gaynor"\nMackie"", featuring Bob Mackie\'s Emmy-winning costumes from her specials along with a selection of costumes from Gaynor\'s legendary stage shows and concert appearances. On October 14, 2006, the ""NY Alumni"" ""adopted"" Gaynor as an official ""New Yorker"" at Beverly Hills High School. New York City mayor Michael Bloomberg issued a proclamation paying tribute to her distinguished career as a singer, dancer, actress and writer. On October 14, 1968, Gaynor starred in her first television special, ""Mitzi"". In specials including ""Mitzi – The First Time"" and ""Mitzi ... Zings into Spring"" she showcased the talents she had first used as a']

### Rerank using cross-encoder/ms-marco-MiniLM-L6-v2

In [7]:
cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L6-v2')

top_k = pl.DataFrame(cross_encoder.rank(prompt,docs,top_k=3,return_documents=True))
top_k.get_column('text').to_list()

['"Mitzi Gaynor"\nMitzi Gaynor Mitzi Gaynor (born Francesca Marlene de Czanyi von Gerber; September 4, 1931) is an American actress, singer, and dancer. Her notable films include ""There\'s No Business Like Show Business"" (1954), which featured Irving Berlin\'s music and also starred Ethel Merman, Dan Dailey, Marilyn Monroe, Donald O\'Connor, and Johnnie Ray; and ""South Pacific"", the 1958 motion picture adaptation of the stage musical by Rodgers and Hammerstein. Mitzi Gaynor was born as Francesca Marlene de Czanyi von Gerber on September 4, 1931, in Chicago, Illinois, the daughter of Pauline, a dancer, and Henry von Gerber, a violinist, cellist, and music',
 '"Mitzi Gaynor"\nis the best thing since... ""Mitzi Gaynor!"" Lisa exclaims. In episode 2 of ""Monty Python\'s Fliegender Zirkus"", Connie Booth played Princess Mitzi Gaynor in ""The Tale of Happy Valley"". Mitzi Gaynor is mentioned on ""The Marvelous Mrs. Maisel"" in Episode 4, ""The Disappointment of the Dionne Quintuplets"". Mitzi Gaynor Mitzi Gaynor (born Francesca Marlene de Czanyi von Gerber; September 4, 1931) is an American actress, singer, and dancer. Her notable films include ""There\'s No Business Like Show Business"" (1954), which featured Irving Berlin\'s music and also starred Ethel Merman, Dan Dailey, Marilyn Monroe, Donald O\'Connor, and Johnnie Ray; and ""South',
 '"Mitzi Gaynor"\nfilm musicals, often paired with some of the biggest male musical stars of the day. A Fox Studio executive thought that Mitzi Gerber sounded like the name of a delicatessen, and they came up with a name that used the same initials. Gaynor made her film debut in a musical, ""My Blue Heaven"" (1950) supporting Betty Grable and Dan Dailey. She followed it with a college drama ""Take Care of My Little Girl"" (1951), where she played the roommate of Jeanne Crain. Fox then gave Gaynor a star part, in the musical biopic ""Golden Girl"" (1951), playing Lotta Crabtree. It']

## 2. Qwen2.5

In [8]:
# Code mostly taken directly from huggingface: https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct

model_name = "Qwen/Qwen2.5-0.5B-Instruct"

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    dtype="auto",
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained(model_name)

messages = [
    {"role": "system", "content": "You are a helpful assistant, answer the user's question in markdown"},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

generated_ids = model.generate(
    **model_inputs,
    max_new_tokens=2048
)
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
display(Markdown(response))

Mitzi Gaynor is an American actress known for her roles in films such as "The Departed," "Crazy Rich Asians," and "Inception." She gained recognition for her portrayal of the character Rachel Green on the TV show "The Fresh Prince of Bel-Air" from 2013 to 2014. In addition to acting, she has also worked in various other film projects. Mitzi Gaynor is a well-known figure in Hollywood and has received multiple awards for her performances.

## 3. RAG with Uncertainty Estimation

### 3.1 Retriever

In [9]:
bm25 = LuceneSearcher('index/wiki_dump')
cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L6-v2')

def get_top_3_rerank(query: str) -> str:
    """Using the user query, this function retrieves the three most relevant models using rerank

    Args:
        query (str): the user query

    Returns:
        str: a string containing the top three documents.
    """    
    hits = bm25.search(query,k=1000)

    docs = [json.loads(hits[i].lucene_document.get('raw'))["contents"] for i in range(len(hits))]
    

    top_k = pl.DataFrame(cross_encoder.rank(query,docs,top_k=3,return_documents=True))
    
    return "- "+"\n- ".join(top_k.get_column('text').to_list())

display(Markdown(get_top_3_rerank(prompt)))

- "Mitzi Gaynor"
Mitzi Gaynor Mitzi Gaynor (born Francesca Marlene de Czanyi von Gerber; September 4, 1931) is an American actress, singer, and dancer. Her notable films include ""There's No Business Like Show Business"" (1954), which featured Irving Berlin's music and also starred Ethel Merman, Dan Dailey, Marilyn Monroe, Donald O'Connor, and Johnnie Ray; and ""South Pacific"", the 1958 motion picture adaptation of the stage musical by Rodgers and Hammerstein. Mitzi Gaynor was born as Francesca Marlene de Czanyi von Gerber on September 4, 1931, in Chicago, Illinois, the daughter of Pauline, a dancer, and Henry von Gerber, a violinist, cellist, and music
- "Mitzi Gaynor"
is the best thing since... ""Mitzi Gaynor!"" Lisa exclaims. In episode 2 of ""Monty Python's Fliegender Zirkus"", Connie Booth played Princess Mitzi Gaynor in ""The Tale of Happy Valley"". Mitzi Gaynor is mentioned on ""The Marvelous Mrs. Maisel"" in Episode 4, ""The Disappointment of the Dionne Quintuplets"". Mitzi Gaynor Mitzi Gaynor (born Francesca Marlene de Czanyi von Gerber; September 4, 1931) is an American actress, singer, and dancer. Her notable films include ""There's No Business Like Show Business"" (1954), which featured Irving Berlin's music and also starred Ethel Merman, Dan Dailey, Marilyn Monroe, Donald O'Connor, and Johnnie Ray; and ""South
- "Mitzi Gaynor"
film musicals, often paired with some of the biggest male musical stars of the day. A Fox Studio executive thought that Mitzi Gerber sounded like the name of a delicatessen, and they came up with a name that used the same initials. Gaynor made her film debut in a musical, ""My Blue Heaven"" (1950) supporting Betty Grable and Dan Dailey. She followed it with a college drama ""Take Care of My Little Girl"" (1951), where she played the roommate of Jeanne Crain. Fox then gave Gaynor a star part, in the musical biopic ""Golden Girl"" (1951), playing Lotta Crabtree. It

### 3.2 LLM

In [10]:
# Code mostly taken directly from huggingface: https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct

model_name = "Qwen/Qwen2.5-0.5B-Instruct"

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    dtype="auto",
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained(model_name)

def messages_from_prompt_query(prompt, query):
    return [
        {"role": "system", "content": prompt},
        {"role": "user", "content": query}
    ]

def response_from_prompt(prompt, query):
    messages = messages_from_prompt_query(prompt,query)
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

    generated_ids = model.generate(
        **model_inputs,
        max_new_tokens=2048
    )
    generated_ids = [
        output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
    ]

    return tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
display(Markdown(response_from_prompt("You are a helpful assistant, answer the user's question in markdown",prompt)))

Mitzi Gaynor is an American actress who gained significant popularity in the 1970s and early 1980s with her role as the character Miss America in "Miss America" (1972-1974). She was known for her strong, assertive personality and her ability to bring authenticity to her performances. Gaynor's acting career also included roles in "The Young and the Restless" (1973), "The Goonies" (1985), and "The Adventures of Tintin" (1963-1966). In addition to her acting career, she has been involved in writing and directing various productions. Mitzi Gaynor passed away on October 21, 2023.

### 3.3 Uncertainty Estimation

In [19]:
# Define truth methods
mars = ttlm.truth_methods.MARS()
eccentricity = ttlm.truth_methods.EccentricityUncertainty()
truth_methods = [mars, eccentricity]

def get_llm_answer_with_ue_values(messages):
    output_hf_model = ttlm.generate_with_truth_value(
        model=model,
        tokenizer=tokenizer,
        messages=messages,
        truth_methods=truth_methods,
        max_new_tokens=1024
    )
    return { "query" : messages[1]["content"]
         , "response" : output_hf_model["generated_text"]
         , "MARS" : output_hf_model["unnormalized_truth_values"][0]
         , "MARS_normalized" : output_hf_model["normalized_truth_values"][0]
         , "Eccentricity" : output_hf_model["unnormalized_truth_values"][1]
         , "Eccentricity_normalized" : output_hf_model["normalized_truth_values"][1]
         }
get_llm_answer_with_ue_values(messages)

There are 2 methods for similarity: semantic similarity and jaccard score. The default method is semantic similarity. If you want to use jaccard score, please set method_for_similarity="jaccard". Please refer to https://arxiv.org/pdf/2305.19187 for more information.

OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 MiB. GPU 0 has a total capacity of 7.62 GiB of which 9.19 MiB is free. Including non-PyTorch memory, this process has 7.59 GiB memory in use. Of the allocated memory 7.40 GiB is allocated by PyTorch, and 34.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

### 3.4 Final Combination - RAG

In [12]:
prompt_template = """
You are a helpful assistant that uses context to answer a question. You always answer in markdown. Make sure to use only relevant context in your answer.
    
The following context is provided\n
{context}
    
Now answer the following question:
"""
    
def rag_with_ue(query):
    context = get_top_3_rerank(query)
    
    messages = messages_from_prompt_query(prompt_template.format(context=context),query)
    
    return get_llm_answer_with_ue_values(messages)

result = rag_with_ue(prompt)
print(f"Answered with uncertainty estimates for MARS: {result["MARS_normalized"]} and Eccentricity: {result["Eccentricity_normalized"]}:")
display(Markdown(result["response"]))

Answered with uncertainty estimates for MARS: 0.30975845970955795 and Eccentricity: 0.49659476256045326:

Based on the information provided:

Mitzi Gaynor is an American actress, singer, and dancer who gained significant recognition for her roles in various films during the 1950s and early 1960s. Her most famous work includes starring in iconic musicals such as "There's No Business Like Show Business" (1954) and later appearing in "South Pacific." Gaynor's career spanned several decades, beginning with her appearance in "My Blue Heaven" (1950) and continuing through her role in "Take Care of My Little Girl" (1951). Throughout her career, Gaynor had the opportunity to work alongside other major musical acts of the era, including Ethel Merman, Dan Dailey, Marilyn Monroe, Donald O'Connor, and Johnnie Ray. The fact that she has been able to maintain her status in Hollywood despite her age suggests she has maintained a level of popularity and influence over time.

In [13]:
def ue_and_rag_from_prompts(prompts : list[str]) -> pl.DataFrame:
    """_summary_

    Args:
        prompts (list[str]): _description_

    Returns:
        pl.DataFrame: _description_
    """   
    return pl.DataFrame([rag_with_ue(p) for p in tqdm(prompts)]) 
result_frame = ue_and_rag_from_prompts(prompts)
result_frame

100%|██████████| 50/50 [22:06<00:00, 26.54s/it]

shape: (50, 5)
┌───────────────────────────┬───────────┬─────────────────┬──────────────┬─────────────────────────┐
│ response                  ┆ MARS      ┆ MARS_normalized ┆ Eccentricity ┆ Eccentricity_normalized │
│ ---                       ┆ ---       ┆ ---             ┆ ---          ┆ ---                     │
│ str                       ┆ f64       ┆ f64             ┆ f64          ┆ f64                     │
╞═══════════════════════════╪═══════════╪═════════════════╪══════════════╪═════════════════════════╡
│ Mitzi Gaynor is an        ┆ -0.541243 ┆ 0.367898        ┆ -1.638094    ┆ 0.162725                │
│ American ac…              ┆           ┆                 ┆              ┆                         │
│ Based on the information  ┆ -0.479072 ┆ 0.382471        ┆ -0.009683    ┆ 0.497579                │
│ provi…                    ┆           ┆                 ┆              ┆                         │
│ Based on the information  ┆ -0.607832 ┆ 0.352554        ┆ -0.018581    ┆ 0.495355                │
│ provi…                    ┆           ┆                 ┆              ┆                         │
│ Certainly! Here's a brief ┆ -0.96738  ┆ 0.275403        ┆ -0.00981     ┆ 0.497548                │
│ biog…                     ┆           ┆                 ┆              ┆                         │
│ Based on the information  ┆ -0.972669 ┆ 0.274349        ┆ -0.009343    ┆ 0.497664                │
│ provi…                    ┆           ┆                 ┆              ┆                         │
│ …                         ┆ …         ┆ …               ┆ …            ┆ …                       │
│ Based on the information  ┆ -0.812704 ┆ 0.307315        ┆ -0.003939    ┆ 0.499015                │
│ provi…                    ┆           ┆                 ┆              ┆                         │
│ Based on the information  ┆ -0.667204 ┆ 0.339123        ┆ -0.007734    ┆ 0.498067                │
│ provi…                    ┆           ┆                 ┆              ┆                         │
│ The Kyoto Protocol, also  ┆ -0.852827 ┆ 0.29884         ┆ -0.014287    ┆ 0.496428                │
│ known…                    ┆           ┆                 ┆              ┆                         │
│ Based on the information  ┆ -0.571352 ┆ 0.360925        ┆ -0.006797    ┆ 0.498301                │
│ provi…                    ┆           ┆                 ┆              ┆                         │
│ The Danube River is a     ┆ -1.069265 ┆ 0.255543        ┆ -0.007605    ┆ 0.498099                │
│ signific…                 ┆           ┆                 ┆              ┆                         │
└───────────────────────────┴───────────┴─────────────────┴──────────────┴─────────────────────────┘

In [ ]:
result_frame.write_parquet("data/answers/answers_with_ue.parquet")

In [21]:
df = pl.read_parquet('/home/rijkk/Documents/Information Retrieval/rag-uncertainty-longform/src/data/answers/answers_with_ue.parquet')
df

shape: (50, 6)
┌─────────────────┬─────────────────┬───────────┬─────────────────┬──────────────┬─────────────────┐
│ query           ┆ response        ┆ MARS      ┆ MARS_normalized ┆ Eccentricity ┆ Eccentricity_no │
│ ---             ┆ ---             ┆ ---       ┆ ---             ┆ ---          ┆ rmalized        │
│ str             ┆ str             ┆ f64       ┆ f64             ┆ f64          ┆ ---             │
│                 ┆                 ┆           ┆                 ┆              ┆ f64             │
╞═════════════════╪═════════════════╪═══════════╪═════════════════╪══════════════╪═════════════════╡
│ Question: Tell  ┆ Mitzi Gaynor is ┆ -0.541243 ┆ 0.367898        ┆ -1.638094    ┆ 0.162725        │
│ me a bio of     ┆ an American ac… ┆           ┆                 ┆              ┆                 │
│ Mit…            ┆                 ┆           ┆                 ┆              ┆                 │
│ Question: Tell  ┆ Based on the    ┆ -0.479072 ┆ 0.382471        ┆ -0.009683    ┆ 0.497579        │
│ me a bio of     ┆ information     ┆           ┆                 ┆              ┆                 │
│ Ger…            ┆ provi…          ┆           ┆                 ┆              ┆                 │
│ Question: Tell  ┆ Based on the    ┆ -0.607832 ┆ 0.352554        ┆ -0.018581    ┆ 0.495355        │
│ me a bio of     ┆ information     ┆           ┆                 ┆              ┆                 │
│ War…            ┆ provi…          ┆           ┆                 ┆              ┆                 │
│ Question: Tell  ┆ Certainly!      ┆ -0.96738  ┆ 0.275403        ┆ -0.00981     ┆ 0.497548        │
│ me a bio of     ┆ Here's a brief  ┆           ┆                 ┆              ┆                 │
│ Sit…            ┆ biog…           ┆           ┆                 ┆              ┆                 │
│ Question: Tell  ┆ Based on the    ┆ -0.972669 ┆ 0.274349        ┆ -0.009343    ┆ 0.497664        │
│ me a bio of     ┆ information     ┆           ┆                 ┆              ┆                 │
│ Pri…            ┆ provi…          ┆           ┆                 ┆              ┆                 │
│ …               ┆ …               ┆ …         ┆ …               ┆ …            ┆ …               │
│ What are the    ┆ Based on the    ┆ -0.812704 ┆ 0.307315        ┆ -0.003939    ┆ 0.499015        │
│ key             ┆ information     ┆           ┆                 ┆              ┆                 │
│ architectural…  ┆ provi…          ┆           ┆                 ┆              ┆                 │
│ What can you    ┆ Based on the    ┆ -0.667204 ┆ 0.339123        ┆ -0.007734    ┆ 0.498067        │
│ tell me about   ┆ information     ┆           ┆                 ┆              ┆                 │
│ the…            ┆ provi…          ┆           ┆                 ┆              ┆                 │
│ What is known   ┆ The Kyoto       ┆ -0.852827 ┆ 0.29884         ┆ -0.014287    ┆ 0.496428        │
│ about the Kyoto ┆ Protocol, also  ┆           ┆                 ┆              ┆                 │
│ …               ┆ known…          ┆           ┆                 ┆              ┆                 │
│ What can you    ┆ Based on the    ┆ -0.571352 ┆ 0.360925        ┆ -0.006797    ┆ 0.498301        │
│ tell me about   ┆ information     ┆           ┆                 ┆              ┆                 │
│ the…            ┆ provi…          ┆           ┆                 ┆              ┆                 │
│ What can you    ┆ The Danube      ┆ -1.069265 ┆ 0.255543        ┆ -0.007605    ┆ 0.498099        │
│ tell me about   ┆ River is a      ┆           ┆                 ┆              ┆                 │
│ the…            ┆ signific…       ┆           ┆                 ┆              ┆                 │
└─────────────────┴─────────────────┴───────────┴─────────────────┴──────────────┴─────────────────┘